"""Add image_url to Exercise

Revision ID: 1d3fbf68a969
Revises: a5b77ebabbe3
Create Date: 2024-02-02 13:43:54.040443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3fbf68a969'
down_revision = 'a5b77ebabbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
