"""validation

Revision ID: 43695e84a6e6
Revises: 1d3fbf68a969
Create Date: 2024-02-02 16:02:33.655984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43695e84a6e6'
down_revision = '1d3fbf68a969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
